### ISSUE TITLE
sort by most reacted

### ISSUE THREAD

**Issue by petersopko** [kodadot/rubick#121]
as discussed in the issue linked below, we lost most reacted sorting option by going from magick to rubick

https://github.com/kodadot/nft-gallery/issues/3707

**Comment by vikiival** [comment]
So the setup:
- extend the NFTEntity in schema with `emoteCount: Int!`
- in mint function set `emoteCount = 0`
- when NFT is emoted set `emoteCount += 1`
- when NFT is un-emoted set `emoteCount -= 1`

aaaaaaand that's it.

Of course do not forget to make `build`, `codegen`, `migrate` after you update the schema. 

Currently this is blocked by #117 (try to fix all stuff today)


may @Jarsen136 wanna pick it up?

**Comment by Jarsen136** [comment]
Thanks for explaining it. I will have a try.

**Comment by vikiival** [comment]
It needs a manual migration to update the existing NFTs without a need to reindex the whole chain :)
