### ISSUE TITLE
Create `release-009` branch for rmrk2

### ISSUE THREAD

**Issue by roiLeo** [kodadot/rubick#185]
- https://github.com/kodadot/rubick/tree/zlozenec

**Comment by vikiival** [comment]
There is already 009-rc0

009 will merge both

**Comment by roiLeo** [comment]
> There is already 009-rc0

❓ 
![Screenshot 2023-02-23 at 15-57-23 Branches · kodadot_rubick](https://user-images.githubusercontent.com/9987732/220943428-7a5bb303-5577-4322-a1b0-f769228acecd.png)
