### ISSUE TITLE
Resources on lastEvent query for rmrk2

### ISSUE THREAD

**Issue by roiLeo** [kodadot/rubick#203]
> from @preschian 

currently lastEvent query on rmrk2 doesn't have `resources` field

https://squid.subsquid.io/rubick/v/009-rc0/graphql

<img width="177" alt="Screenshot 2023-03-29 at 13 45 50" src="https://user-images.githubusercontent.com/734428/228448808-ef087bb1-7e82-408f-8803-a9368fec26a0.png">

**Comment by vikiival** [comment]
Hey, I do not have currently time to implement this feature. 

Happy to review and test PR. 
Otherwise a bit of hacking needs to be done
