### ISSUE TITLE
passion feed resolver

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#27]
```sql
SELECT DISTINCT ne.issuer
FROM nft_entity ne
WHERE ne.current_owner = $0
AND ne.current_owner != ne.issuer
```

**Comment by KngZhi** [comment]
Hello, @vikiival is this p1 for your, if so, I will take it.

**Comment by vikiival** [comment]
@petersopko does the assign bot work in other repositories?

**Comment by petersopko** [comment]
> @petersopko does the assign bot work in other repositories?

not yet, but it can!
