### ISSUE TITLE
Auto publish Squid

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#38]
Create a branch (e.g `005`)
Gh action should update the squid (`just improve 005`)

**Comment by yangwao** [comment]
Hey @KngZhi, if you could help us on this would be doable

**Comment by vikiival** [comment]
@preschian maybe?

**Comment by preschian** [comment]
> @preschian maybe?

sure, would love to take this later. I need to signup to subsquid first to get familiar with the dashboard
