### ISSUE TITLE
User Entity

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#52]
We are slowly getting to the tipping point where we need to replace user as `String!` with `UserEntity`

Would would it do?:
- cache various metrics
- calculating scores

Similarly to 
https://github.com/kodadot/magick/issues/19

@yangwao, @roiLeo please drop your thoughts

**Comment by roiLeo** [comment]
Will we be able to retrieve displayname in UserEntity? or should we have an IdentityEntity instead?

**Comment by vikiival** [comment]
> Will we be able to retrieve displayname in UserEntity?

that should be a job of kodadot/hei 

The problem is that this indexer starts around block 5 million, so anyone who set identity before yould be sad :/

**Comment by yangwao** [comment]
Would it be possible to show users activity? Like the history chart we have for collections but for users?

What scores do you have in mind?

**Comment by vikiival** [comment]
ref #56

**Comment by vikiival** [comment]
Continue in https://github.com/kodadot/loligo/issues/49
