### ISSUE TITLE
Identity/ User entity (codename: hei)

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#56]
I spoke with @dzhelezov today and he told me that you can specify from each block the handler should be active: 

That means we can fetch the identities from the block 1 and `system.remark` as is (block 5 mil)

maybe @roiLeo wanna take a spin? 👀 (happy to provide support)

**Comment by dzhelezov** [comment]
Yeah 'HandlerOptions' has a 'Range' property exactly for that. The last version of the lib has a good inline documentation so you guys can rely on intellisense in vscode

**Comment by roiLeo** [comment]
Is the starting block specified in `processor.setBlockRange({from:5756453});`? Why do we need to start at 5 million?
Do you know approximately how long will it take?

**Comment by dzhelezov** [comment]
`processor.setBlockRange` sets the global range for _all_ block handlers. In your case, you need to have to set a range only for a specific handler (for `system.remark`, as far as I understood). This can be done with 

```
processor.addEventHandler("system.remark", { range: { from: 5756453 } }, async (ctx) => {
//
}
```
For more options, see the inline docs popping up in vscode. Extrinsic handlers can be configured similarly.

**Comment by vikiival** [comment]
Q is do we want to spin up a new multichain indexer as a common good or will we hack it into rubick ? 


```graphql
type Account @entity {
    id: ID!
    collections: [Collection!] @derivedFrom(field: "issuer")
    nfts: [NFT!] @derivedFrom(field: "issuer")
    # unwrap all identity fields here
}

```

**Comment by vikiival** [comment]
Meanwhile fixed by giant squid
