### ISSUE TITLE
Different result between magick & rubick

### ISSUE THREAD

**Issue by roiLeo** [kodadot/rubick#59]
Why is there any difference in result? (216 vs 222)
Which one is up to date?

### magick
```graphql
query nftListLiked($account: String!, $first: Int!, $offset: Int) {
  emotes(
    filter: { caller: { equalTo: $account } }
    first: $first
    offset: $offset
    orderBy: ID_DESC
  ) {
    totalCount
    nodes {
      id
      value
      caller
      nft {
        id
        issuer
        collectionId
        name
      }
    }
  }
}
```

![Capture d’écran 2022-04-26 à 5 03 34 PM](https://user-images.githubusercontent.com/9987732/165331350-b5ccae41-6f38-4100-b558-35ac381d3199.png)

### rubick
```graphql
query nftListLiked($account: String!, $first: Int!, $offset: Int) {
  stats: emotesConnection(orderBy: id_DESC, where: { caller_eq: $account }) {
    totalCount
  }
  emotes(
    limit: $first
    offset: $offset
    orderBy: id_DESC
    where: { caller_eq: $account }
  ) {
    id
    value
    caller
    nft {
      id
      issuer
      name
      currentOwner
    }
  }
}
```

![Capture d’écran 2022-04-26 à 5 03 47 PM](https://user-images.githubusercontent.com/9987732/165331386-9d104981-9090-4107-a8bf-eee0bd811851.png)

### variables
`{"first": 20, "offset": 0, "account": "FJMJLAVCv1KG3UXBh1Hr54VzHsEF4MQTC4nZrZUUucbEsKJ"}`

**Comment by vikiival** [comment]
Meanwhile `magick` was deprecated
