### ISSUE TITLE
Migration bug

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#61]
https://github.com/kodadot/rubick/commit/e69bee871f208c1b701e0d8c2e24a97d828d0bb7

**Comment by vikiival** [comment]
@KngZhi out of computer rn. Will fix later

**Comment by KngZhi** [comment]
hi @vikiival, I think the current DB migration caused an error that does not show highest_sale properly.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/11361147/166430501-8bd89ea3-c1ca-4881-9e8a-c0fd835c6793.png">

**Comment by vikiival** [comment]
Looks like something is super fokked :)

**Comment by KngZhi** [comment]
😂

**Comment by vikiival** [comment]
:)

```graphql
query MyQuery {
  series {
    highestSale
  }
}
```

migration should be oki 

[check by yourself](https://app.gc.subsquid.io/beta/rubick/006/graphql)

**Comment by KngZhi** [comment]
nothing returned.

![image](https://user-images.githubusercontent.com/11361147/166478169-69dcbec2-0138-4297-a491-d1ab42d4121b.png)

**Comment by KngZhi** [comment]
#66 I manually add this migration fix at local dev, run migration firstly, and do `just process`, I can see data locally right now.

**Comment by KngZhi** [comment]
hmmm, see data right now. Sorry to bother you.

![image](https://user-images.githubusercontent.com/11361147/166480106-61c4ba29-316d-4642-ab29-74883cd75041.png)

**Comment by vikiival** [comment]
> hmmm, see data right now. Sorry to bother you.

No problemo :) ping me anytime
